package com.silasonyango.ndma.ui.county.model

enum class SeasonsResponsesEnum {
    SEASONS_DRY,
    SEASONS_LONG_RAINS,
    SEASONS_SHORT_RAINS,

    /* Crop production responses */
    MAIZE_LAND_PREPARATION,
    CASSAVA_LAND_PREPARATION,
    RICE_LAND_PREPARATION,
    SORGHUM_LAND_PREPARATION,
    LEGUMES_LAND_PREPARATION,

    MAIZE_PLANTING,
    CASSAVA_PLANTING,
    RICE_PLANTING,
    SORGHUM_PLANTING,
    LEGUMES_PLANTING,

    MAIZE_HARVESTING,
    CASSAVA_HARVESTING,
    RICE_HARVESTING,
    SORGHUM_HARVESTING,
    LEGUMES_HARVESTING
}