package com.ndma.livelihoodzones.config

object Constants {
    val QUESTIONNAIRES_LIST_OBJECT = "questionsListObject"

    val WEALTH_GROUP_LIST_OBJECT = "wealthGroupListObject"

    val GEOGRAPHY_OBJECT = "geographyObject"

    val QUESTIONNAIRE_COMPLETED = "QUESTIONNAIRE_COMPLETED"

    val LZ_CROPS_NEXT_BUTTON_CLICKED = "LZ_CROPS_NEXT_BUTTON_CLICKED"

    val DISMISS_MAIN_ACTIVITY_DIALOGS = "DISMISS_MAIN_ACTIVITY_DIALOGS"

    val RESUME_ZONAL_QUESTIONNAIRE = "RESUME_ZONAL_QUESTIONNAIRE"

    val RESUME_WEALTH_GROUP_QUESTIONNAIRE = "RESUME_WEALTH_GROUP_QUESTIONNAIRE"

    val RESUME_QUESTIONNAIRE_ID = "RESUME_QUESTIONNAIRE_ID"

    val EXISTING_ACCOUNT = "EXISTING_ACCOUNT"

    /* County level steps */
    const val LIVELIHOOD_ZONE_CHARACTERISTICS_STEP = 1
    const val ZONE_SUBLOCATION_ASSIGNMENT_STEP = 2
    const val WEALTH_GROUP_CHARACTERISTICS_STEP = 3
    const val WEALTH_GROUP_PERCENTAGES_STEP = 4
    const val LZ_CROP_SELECTION_STEP = 5
    const val LZ_CROP_PRODUCTION_STEP = 6
    const val MAIN_SOURCES_OF_WATER_STEP = 7
    const val MARKETS_CONFIGURATION_STEP = 8
    const val MARKETS_TRANSACTIONS_STEP = 9
    const val ETHNIC_GROUP_SELECTION_STEP = 10
    const val ETHNIC_GROUP_POPULATION_STEP = 11
    const val HUNGER_PATTERNS_STEP = 12
    const val HAZARDS_STEP = 13
    const val SEASON_CALENDAR_STEP = 14
    const val LZ_COMPLETION_PAGE = 15

    /* Zonal level steps */
    const val MAIN_INCOME_AND_FOOD_SOURCE_STEP = 1
    const val FOOD_CONSUMPTION_SOURCE_PERCENTAGE_STEP = 2
    const val WG_CROP_SELECTION_STEP = 3
    const val WG_CROP_PRODUCTION_STEP = 4
    const val LIVESTOCK_POULTRY_NUMBERS_STEP = 5
    const val LIVESTOCK_POULTRY_CONTRIBUTION_STEP = 6
    const val LABOUR_PATTERNS_STEP = 7
    const val EXPENDITURE_PATTERNS_STEP = 8
    const val MIGRATION_PATTERNS_STEP = 9
    const val CONSTRAINTS_STEP = 10
    const val COPING_STRATEGIES_STEP = 11
    const val FGD_PARTICIPANTS_STEP = 12
    const val WG_COMPLETION_PAGE = 13
}