package com.ndma.livelihoodzones.config

object Constants {
    val QUESTIONNAIRES_LIST_OBJECT = "questionsListObject"

    val WEALTH_GROUP_LIST_OBJECT = "wealthGroupListObject"

    val GEOGRAPHY_OBJECT = "geographyObject"

    val QUESTIONNAIRE_COMPLETED = "QUESTIONNAIRE_COMPLETED"

    val LZ_CROPS_NEXT_BUTTON_CLICKED = "LZ_CROPS_NEXT_BUTTON_CLICKED"

    val DISMISS_MAIN_ACTIVITY_DIALOGS = "DISMISS_MAIN_ACTIVITY_DIALOGS"

    val RESUME_ZONAL_QUESTIONNAIRE = "RESUME_ZONAL_QUESTIONNAIRE"

    val RESUME_QUESTIONNAIRE_ID = "RESUME_QUESTIONNAIRE_ID"

    val LIVELIHOOD_ZONE_CHARACTERISTICS_STEP = 1
    val ZONE_SUBLOCATION_ASSIGNMENT_STEP = 2
    val WEALTH_GROUP_CHARACTERISTICS_STEP = 3
}