package com.ndma.livelihoodzones.config

object Constants {
    val QUESTIONNAIRES_LIST_OBJECT = "questionsListObject"

    val WEALTH_GROUP_LIST_OBJECT = "wealthGroupListObject"

    val GEOGRAPHY_OBJECT = "geographyObject"

    val QUESTIONNAIRE_COMPLETED = "QUESTIONNAIRE_COMPLETED"

    val LZ_CROPS_NEXT_BUTTON_CLICKED = "LZ_CROPS_NEXT_BUTTON_CLICKED"

    val DISMISS_MAIN_ACTIVITY_DIALOGS = "DISMISS_MAIN_ACTIVITY_DIALOGS"

    val RESUME_ZONAL_QUESTIONNAIRE = "RESUME_ZONAL_QUESTIONNAIRE"

    val RESUME_WEALTH_GROUP_QUESTIONNAIRE = "RESUME_WEALTH_GROUP_QUESTIONNAIRE"

    val RESUME_QUESTIONNAIRE_ID = "RESUME_QUESTIONNAIRE_ID"

   /* County level steps */
    val LIVELIHOOD_ZONE_CHARACTERISTICS_STEP = 1
    val ZONE_SUBLOCATION_ASSIGNMENT_STEP = 2
    val WEALTH_GROUP_CHARACTERISTICS_STEP = 3

   /* Zonal level steps */
    val MAIN_INCOME_AND_FOOD_SOURCE_STEP = 1;
    val FOOD_CONSUMPTION_SOURCE_PERCENTAGE_STEP = 2;
    val WG_CROP_SELECTION_STEP = 3;
    val WG_CROP_PRODUCTION_STEP = 4;
}