package com.ndma.livelihoodzones.ui.county.responses

class HazardResponses() {
    var animalRustling = HazardResponseItem(0,0.0)
    var banditry = HazardResponseItem(0,0.0)
    var terrorism = HazardResponseItem(0,0.0)
    var ethnicConflict = HazardResponseItem(0,0.0)
    var politicalViolence = HazardResponseItem(0,0.0)
    var drought = HazardResponseItem(0,0.0)
    var livestockPestsAndDiseases = HazardResponseItem(0,0.0)
    var hailstormsOrFrost = HazardResponseItem(0,0.0)
    var flooding = HazardResponseItem(0,0.0)
    var landslides = HazardResponseItem(0,0.0)
    var highWindsOrCyclones = HazardResponseItem(0,0.0)
    var bushFires = HazardResponseItem(0,0.0)
    var cropPests = HazardResponseItem(0,0.0)
    var locustInvasion = HazardResponseItem(0,0.0)
    var cropDiseases = HazardResponseItem(0,0.0)
    var terminalIllnesses = HazardResponseItem(0,0.0)
    var malariaPowerOutBreak = HazardResponseItem(0,0.0)
    var waterBornDiseases = HazardResponseItem(0,0.0)
    var humanWildlifeConflict = HazardResponseItem(0,0.0)
    var highFoodPrices = HazardResponseItem(0,0.0)
    var marketFoodShortages = HazardResponseItem(0,0.0)
    var drinkingWaterShortages = HazardResponseItem(0,0.0)
    var invasivePlants = HazardResponseItem(0,0.0)
    var others = HazardResponseItem(0,0.0)
}