package com.ndma.livelihoodzones.ui.county.responses

class HazardResponses() {
    var animalRustling = HazardResponseItem(-1,0.0)
    var banditry = HazardResponseItem(-1,0.0)
    var terrorism = HazardResponseItem(-1,0.0)
    var ethnicConflict = HazardResponseItem(-1,0.0)
    var politicalViolence = HazardResponseItem(-1,0.0)
    var drought = HazardResponseItem(-1,0.0)
    var livestockPestsAndDiseases = HazardResponseItem(-1,0.0)
    var hailstormsOrFrost = HazardResponseItem(-1,0.0)
    var flooding = HazardResponseItem(-1,0.0)
    var landslides = HazardResponseItem(-1,0.0)
    var highWindsOrCyclones = HazardResponseItem(-1,0.0)
    var bushFires = HazardResponseItem(-1,0.0)
    var cropPests = HazardResponseItem(-1,0.0)
    var locustInvasion = HazardResponseItem(-1,0.0)
    var cropDiseases = HazardResponseItem(-1,0.0)
    var terminalIllnesses = HazardResponseItem(-1,0.0)
    var malariaPowerOutBreak = HazardResponseItem(-1,0.0)
    var waterBornDiseases = HazardResponseItem(-1,0.0)
    var humanWildlifeConflict = HazardResponseItem(-1,0.0)
    var highFoodPrices = HazardResponseItem(-1,0.0)
    var marketFoodShortages = HazardResponseItem(-1,0.0)
    var drinkingWaterShortages = HazardResponseItem(-1,0.0)
    var invasivePlants = HazardResponseItem(-1,0.0)
    var others = HazardResponseItem(-1,0.0)
}