package com.ndma.livelihoodzones.ui.county.model

enum class HazardTypeEnum {
    ANIMAL_RUSTLING,
    BANDITRY,
    TERRORISM,
    ETHNIC_CONFLICT,
    POLITICAL_CONFLICT,
    DROUGHT,
    LIVESTOCK_PESTS_DISEASES,
    HAILSTORMS,
    FLOODING,
    LANDSLIDES,
    HIGH_WINDS,
    BUSH_FIRES,
    CROP_PESTS,
    LOCUST_INVASION,
    CROP_DISEASES,
    TERMINAL_ILLNESS,
    MALARIA,
    WATERBORNE_DISEASES,
    HUMAN_WILDLIFE_CONFLICT,
    HIGH_FOOD_PRICES,
    FOOD_SHORTAGE,
    DRINKING_WATER_SHORTAGE,
    INVASIVE_PLANTS,
    OTHERS

}