package com.ndma.livelihoodzones.ui.county.model

enum class SeasonsResponsesEnum {
    SEASONS_DRY,
    SEASONS_LONG_RAINS,
    SEASONS_SHORT_RAINS,

    /* Crop production responses */
    MAIZE_LAND_PREPARATION,
    CASSAVA_LAND_PREPARATION,
    RICE_LAND_PREPARATION,
    SORGHUM_LAND_PREPARATION,
    LEGUMES_LAND_PREPARATION,

    MAIZE_PLANTING,
    CASSAVA_PLANTING,
    RICE_PLANTING,
    SORGHUM_PLANTING,
    LEGUMES_PLANTING,

    MAIZE_HARVESTING,
    CASSAVA_HARVESTING,
    RICE_HARVESTING,
    SORGHUM_HARVESTING,
    LEGUMES_HARVESTING,

    /* Livestock production responses */
    LIVESTOCK_IN_MIGRATION,
    LIVESTOCK_OUT_MIGRATION,
    HIGH_MILK_PRODUCTION,
    LOW_MILK_PRODUCTION,
    HIGH_CALVING,
    LOW_CALVING,
    HIGH_KIDDING,
    LOW_KIDDING,
    HIGH_FOOD_PRICES,
    MEDIUM_FOOD_PRICES,
    LOW_FOOD_PRICES,
    HIGH_LIVESTOCK_PRICES,
    MEDIUM_LIVESTOCK_PRICES,
    LOW_LIVESTOCK_PRICES,

    /* Others */
    HIGH_CASUAL_LABOUR_AVAILABILITY,
    LOW_CASUAL_LABOUR_AVAILABILITY,
    NON_AGRIC_HIGH_CASUAL_LABOUR_AVAILABILITY,
    NON_AGRIC_LOW_CASUAL_LABOUR_AVAILABILITY,
    HIGH_CASUAL_LABOUR_WAGES,
    LOW_CASUAL_LABOUR_WAGES,
    HIGH_REMITTANCES,
    LOW_REMITTANCES,
    HIGH_FISHING,
    LOW_FISHING,
    HIGH_MARKET_ACCESS,
    LOW_MARKET_ACCESS,
    HIGH_DISEASE_OUTBREAK,
    LOW_DISEASE_OUTBREAK,
    WATER_STRESS,
    CONFLICT_RISK,
    CEREMONIES,
    LEAN_SEASONS,
    FOOD_SECURITY_ASSESSMENTS,

    DYNAMIC_LAND_PREPARATION

}